name: Docgen and go fmt

on:
  workflow_dispatch:
  push:
    branches: ['main', 'release-*']
  pull_request:

jobs:
  docgen:
    name: Verify Docgen
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - run: ./scripts/verify-docs.sh
  fmt:
    name: Verify go fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - run: test -z $(go fmt ./...)
